// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wallet.Infrastructure.Persistence.Context;

#nullable disable

namespace Wallet.Infrastructure.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20250704195129_FixClientSeedCreatedAt")]
    partial class FixClientSeedCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wallet.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("Balance")
                        .HasColumnType("float");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("591e5f9e-66d6-46f9-9219-92394bc66d15"),
                            Balance = 1000f,
                            ClientId = new Guid("ea123e52-997c-4afa-9955-215613c6e9a9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 4, 19, 51, 28, 702, DateTimeKind.Unspecified).AddTicks(9547), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5d002f3f-21ac-4911-9c63-15f0cf695c29"),
                            Balance = 500f,
                            ClientId = new Guid("33e285ba-d1e3-40d8-9f18-a2200a22d8c5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 4, 19, 51, 28, 702, DateTimeKind.Unspecified).AddTicks(9549), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Wallet.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea123e52-997c-4afa-9955-215613c6e9a9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 4, 19, 51, 28, 702, DateTimeKind.Unspecified).AddTicks(9488), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "cliente1@email.com",
                            Name = "Cliente 1"
                        },
                        new
                        {
                            Id = new Guid("33e285ba-d1e3-40d8-9f18-a2200a22d8c5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 4, 19, 51, 28, 702, DateTimeKind.Unspecified).AddTicks(9491), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "cliente2@email.com",
                            Name = "Cliente 2"
                        });
                });

            modelBuilder.Entity("Wallet.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountFromId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountToId")
                        .HasColumnType("char(36)");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountFromId");

                    b.HasIndex("AccountToId");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3654fe0-f092-410a-bf9d-56ac13edee39"),
                            AccountFromId = new Guid("591e5f9e-66d6-46f9-9219-92394bc66d15"),
                            AccountToId = new Guid("5d002f3f-21ac-4911-9c63-15f0cf695c29"),
                            Amount = 100f,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 7, 4, 19, 51, 28, 703, DateTimeKind.Unspecified).AddTicks(1069), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Wallet.Domain.Entities.Account", b =>
                {
                    b.HasOne("Wallet.Domain.Entities.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Wallet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Wallet.Domain.Entities.Account", "AccountFrom")
                        .WithMany()
                        .HasForeignKey("AccountFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wallet.Domain.Entities.Account", "AccountTo")
                        .WithMany()
                        .HasForeignKey("AccountToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountFrom");

                    b.Navigation("AccountTo");
                });

            modelBuilder.Entity("Wallet.Domain.Entities.Client", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
